local blacklist = {
	"extrapolate", "onPlatformStanding", "onSeated", "onFallingDown", "onGettingUp", "onDied",
	"toolKeyFrameReachedFunc", "playEmote", "Push", "destroy", "unbindRoot", "unbindNodeDescend",
	"onTextFocusGained", "stepAnimate", "switchToAnim", "NewDisplayModel", "_stopBoundFn",
	"_startBoundFn", "isManifestResolved", "parsePath", "OnSteerLeft", "OnSteerRight",
	"OnThrottleDeccel", "OnThrottleAccel", "Enable", "_reset", "Destroy", "Hide", 
	"GetUser JumpEnabled", "SetUser JumpEnabled", "UpdateJump", "Stop", "Start", 
	"OnTouchEnded", "OnTouchChanged", "OnTouchBegan", "DisconnectEvent", "GetEquippedTool", 
	"maxV", "minV", "Create", "CreateTouchGuiContainer", "SetupAutoPilot", "ComputeSteer", 
	"ComputeThrottle", "_getOrCreateBoundEvent", "getChild", "getCharacter", "getLocalPlayer", 
	"UpdateEnabled", "GetUnreachableWaypointTimeout", "SetUnreachableWaypointTimeout", 
	"GetAgentSizeIncreaseFactor", "SetAgentSizeIncreaseFactor", "GetUseDirectPath", 
	"SetUseDirectPath", "GetIgnoredPartsTag", "GetFailureAnimationEnabled", 
	"SetFailureAnimationEnabled", "GetShowPath", "SetShowPath", "OnRenderStepped", 
	"GetWaypointsAlwaysOnTop", "GetEndWaypointTexture", "GetWaypointRadius", 
	"GetWaypointTexture", "CancelFailureAnimation", "CreateEndWaypoint", "findPlayerHumanoid", 
	"new", "TweenInFrom", "SetIgnoredPartsTag", "SetWaypointsAlwaysOnTop", 
	"SetEndWaypointTexture", "SetWaypointRadius", "SetWaypointTexture", "UpdateMovement", 
	"CleanupPath", "DisconnectEvents", "FindCharacterAncestor", "OnInputEnded", 
	"LayoutMiddleImages", "DoMove", "ConnectGamepadConnectionListeners", "OnNewGamepadConnected", 
	"BindContextActions", "UpdateComfortCamera", "processDeleteChild", "processNode", 
	"OnCharacterAdded", "HandleMoveTo", "CreateWaypointTemplates", "placePathWaypoint", 
	"UpdateActiveControlModuleEnabled", "Reset", "Vel", "queryPoint", "rollAnimation", 
	"scriptChildModified", "SwitchToController", "UpdateTouchGuiVisibility", "OnHumanoidSeated", 
	"getGamepadRightThumbstickPosition", "AverageAngle", "EnableMouseLock", 
	"GetMouseLockOffset", "axisToCFrame", "__call", "CornerBehavior", "MoveBehavior", 
	"_GetFirstPersonLocalOffset", "_GetThirdPersonLocalOffset", "GetSubjectCFrame", 
	"GetCameraHeight", "UpdateEdgeBlur", "OnCurrentCameraChanged", "ResetZoom", 
	"GamepadZoomPress", "LeaveFirstPerson", "stepSpringAxis", "getPitch", "getYaw", 
	"SetCameraToSubjectDistance", "SetInitialOrientation", "StepFreecam", "Pather", 
	"setInputEnabled", "StartFreecam", "getRotation", "MoveStick", "InputInFrame", 
	"FadeThumbstickFrame", "GetIsJumping", "DisconnectGamepadConnectionListeners", 
	"IsMoveVectorCameraRelative", "GetMoveVector", "UpdateJump", "OnTouchMovementModeChange", 
	"OnComputerMovementModeChange", "OnCharacterRemoving", "Disable", "GetActiveController", 
	"NormalizeAngle", "getToolAnim", "rootMotionCompensation", "findExistingAnimationInSet", 
	"IsMouseLocked", "DoMouseLockSwitch", "OnBoundKeysObjectChanged", "GetBindableToggleEvent", 
	"GetIsMouseLocked", "SetSubject", "SetupTransparency", "TeardownTransparency", 
	"CachePartsRecursive", "HasToolAncestor", "OnCameraSubjectChanged", "CharacterRemoving", 
	"CharacterAdded", "GetOcclusionMode", "Reset", "extractRotation", "cframeToAxis", 
	"Cleanup", "GetObscuredParts", "CheckTorsoReference", "LimbMoveBehavior", 
	"LimbBehavior", "Det3x3", "AssertTypes", "yawVelocity", "pitchVelocity", 
	"GetVRFocus", "OnHeadScaleChanged", "GamepadReset", "GetModuleName", "GetAvatarFeetWorldYValue", 
	"setTransform", "getCFrame", "ApplyVRTransform", "GetCameraToSubjectDistance", 
	"LoadNumberValueParameters", "SetAndBoundsCheckDistanceValues", "SetAndBoundsCheckAzimuthValues", 
	"LoadOrCreateNumberValueParameter", "getCamera", "Disconnect", "Connect", "Disable", 
	"_connectCallbacks", "eraseFromEnd", "getTotalTransparency", "Update", "IsInFirstPerson", 
	"OnNewCameraSubject", "GetHumanoidPartToFollow", "CalculateNewLookVectorFromArg", 
	"GetMeasuredDistanceToFocus", "LeaveFirstPerson", "EnterFirstPerson", "InFirstPerson", 
	"GetMouseLockOffset", "SetMouseLockOffset", "GetIsMouseLocked", "SetIsMouseLocked", 
	"GetCameraMovementMode", "SetCameraMovementMode", "GetCameraType", "SetCameraType", 
	"UpdateForDistancePropertyChange", "GetEnabled", "InputTranslationToCameraAngleChange", 
	"OnPlayerCameraPropertyChange", "GetBodyPartToFollow", "Pop", "ActivateCameraController", 
	"keyFrameReachedFunc", "stopAllAnimations", "SelectComputerMovementModule", "Reset", 
	"queryViewport", "StartCapture", "ReleaseSpring", "GetZoomRadius", "GetHumanoid", 
	"GetCameraLookVector", "Cleanup", "OnCurrentCameraChanged", "OnViewportSizeChanged", 
	"GetSubjectRotVelocity", "GetSubjectVelocity", "GetHumanoidRootPart", 
	"setTogglePan", "getTogglePan", "getHoldPan", "getInputEnabled", 
	"resetPanInputCount", "decPanInputCount", "incPanInputCount", "pointerAction", 
	"gamepadReset", "gamepadZoomPress", "keypress", "mouseWheel", "mouseMovement", 
	"isInDynamicThumbstickArea", "adjustTouchPitchSensitivity", "getMouse", 
	"toSCurveSpace", "RotateVectorByAngleAndRound", "IsFiniteVector3", 
	"OnPlayerAdded", "Update", "OnUser GameSettingsPropertyChanged", "MouseWheel", 
	"Trigger", "Thumb", "MousePan", "GpButton", "Keypress", "characterRemoving", 
	"characterAdded", "OnTap", "initializeSoundSystem", "playToolAnimation", 
	"StopFreecam", "Pan", "SetWaypointsAlwaysOnTop", "SetEndWaypointTexture", 
	"SetWaypointRadius", "SetWaypointTexture", "SmartCircleBehavior", 
	"UpdateStepRotation", "UpdateRotationCamera", "StartVREdgeBlur", 
	"UpdateImmersionCamera", "getCollisionPoint", "updateProjection", 
	"testPromotion", "UpdateMouseBehavior", "GetSubjectCFrame", "resetTouchState", 
	"enableCameraToggleInput", "onFreeFall", "onJumping", "stopToolAnimations", 
	"setAnimationSpeed", "setRunSpeed", "getHeightScale", "CleanupPath", 
	"getTrailDotScale", "createTrailDots", "Enable", "SelectTouchModule", 
	"CharacterOutlineBehavior", "Update", "step", "Popper", "playerRemoving", 
	"playerAdded", "StepZoom", "touchChanged", "touchEnded", "touchBegan", 
	"GetCameraControlChoice", "ActivateOcclusionModule", "GetCameraMovementModeFromSettings", 
	"Fov", "thumbstickCurve", "call", "animateTool", "onSwimming", 
	"onClimbing", "playAnimation", "terminate", "stopPlayingLoopedSounds", 
	"configureAnimationSet", "ToggleFreecam", "bindRoot", "Update", 
	"onLocalPlayer", "ShowPathFailedFeedback", "getFailureAnimationTrack", 
	"MoveTo", "Raycast", "Create", "DoFadeInBackground", "FadeThumbstick", 
	"BindContextActions", "updateVRMoveVector", "OnRenderStepped", 
	"calculateRawMoveVector", "GetEstimatedVRTorsoFrame", "Update", 
	"Step", "getRotation", "CalculateNewLookVector", "updateBounds", 
	"stepTargetZoom", "CalculateNewLookCFrameFromArg", "SetCameraToSubjectDistance", 
	"OnCharacterAdded", "_setUpConfigurations", "disableCameraToggleInput", 
	"restoreRotationType", "setRotationTypeOverride", "restoreMouseBehavior", 
	"setMouseBehaviorOverride", "restoreMouseIcon", "setMouseIconOverride", 
	"GamepadLinearToCurve", "onAxis", "playerAdded", "onRunning", 
	"StopCapture", "UpdateIgnoreTag", "CreatePathDisplay", "RunFailureTween", 
	"_StepRotation", "OnEnabledChanged", "GetSubjectPosition", "resetInputDevices", 
	"getZoomDelta", "setSoundLooped", "playSoundIf", "stopSound", "playSound", 
	"loadmodule", "require", "assert", "pcall", "setthreadidentity", 
	"getthreadidentity", "typeof", "disassemble", "decompile", "getcustomasset", 
	"setproperties", "getproperties", "readfileasync", "readfile", "isfolder", 
	"delfolderasync", "movefolderasync", "copyfolder", "makefolder", 
	"listfiles", "isfile", "dofile", "loadfile", "delfile", "movefile", 
	"copyfile", "appendfile", "writefile", "connect", "restoremetamethod", 
	"hookmetamethod", "getmetafield", "hasmetafield", "hasmetatable", 
	"setreadonly", "setrawmetatable", "getrawmetatable", "isreadonly", 
	"getdatamodeltype", "setcalltrace", "getbytecode", "setfpscap", 
	"getfpscap", "setnamecallmethod", "getnamecallmethod", "checkcaller", 
	"getuserdatatag", "getrawaddress", "gethwid", "can_vm_run_native_code", 
	"isnativecode", "disablenative", "enablenative", "enablepointerencoding", 
	"disablepointerencoding", "getstringatom", "getstringhash", "isinstance", 
	"request", "validlevel", "getupvaluecount", "getconstantcount", 
	"getstackcount", "traceback", "info", "getinfo", "setstack", 
	"getstack", "setupvalue", "getupvalue", "getupvalues", "setconstant", 
	"getconstants", "getconstant", "trampoline_call", "ishiddenstack", 
	"sethiddenstack", "comparefunction", "getfunctionhash", "protectfunction", 
	"loadstring", "restorefunction", "iswrappedclosure", "isfunctionprotected", 
	"hookfunction", "clonefunction", "isexecutorclosure", "ishooked", 
	"wrapclosure", "newcclosure", "newlclosure", "islclosure", "iscclosure", 
	"getinstancelist", "getinstances", "getnilinstances", "getconnections", 
	"gethui", "firetouchinterest", "fireproximityprompt", "fireclickdetector", 
	"getsenv", "getcallingscript", "getscriptbytecode", "getscriptclosure", 
	"exchangeinstancepointer", "getsignalargumenttypes", "getsignalargumentnames", 
	"gethiddenproperty", "getcallbackvalue", "invalidatereference", 
	"replacereference", "isreferencevalid", "compareinstances", "cloneref", 
	"stepgc", "gc", "isreferenced", "getgc", "resumegc", "suspendgc", 
	"setclipboard", "gettenv", "messagebox", "httpget", "identifyexecutor", 
	"getscriptglobals", "getgenv", "getreg", "setclipboard", "gettenv", 
	"messagebox", "httpget", "identifyexecutor", "getscriptglobals", 
	"getgenv", "getreg", "DebuggerManager", "cancel", "wait", "delay", 
	"spawn", "defer", "desynchronize", "synchronize", "setfenv", 
	"getfenv", "collectgarbage", "Version", "version", "Stats", "stats", 
	"require", "warn", "PluginManager", "User Settings", "settings", 
	"loadstring", "printidentity", "Spawn", "spawn", "Delay", "delay", 
	"Wait", "wait", "ElapsedTime", "elapsedTime", "time", "tick", 
	"print", "fromCurrent", "new", "fromObject", "fromAssetId", 
	"fromUri", "fromId", "fromName", "fromEnum", "new", "fromIsoDate", 
	"fromLocalTime", "fromUniversalTime", "fromUnixTimestampMillis", 
	"fromUnixTimestamp", "now", "new", "new", "new", "new", "new", 
	"new", "new", "new", "new", "new", "new", "new", "new", "new", 
	"fromExisting", "new", "clear", "update", "size", "increment", 
	"cloneAndFreeze", "clone", "isFrozen", "new", "new", "new", 
	"new", "fromScale", "fromOffset", "new", "new", "Blue", "Green", 
	"Yellow", "Red", "Black", "DarkGray", "Gray", "White", "Random", 
	"New", "palette", "random", "new", "fromHex", "fromHSV", 
	"toHSV", "fromRGB", "new", "new", "max", "min", "new", 
	"max", "min", "fromAxis", "FromAxis", "fromNormalId", 
	"FromNormalId", "new", "new", "new", "new", "new", "new", 
	"fromRotationBetweenVectors", "lookAlong", "lookAt", "fromMatrix", 
	"fromAxisAngle", "fromEulerAngles", "fromOrientation", 
	"fromEulerAnglesYXZ", "Angles", "fromEulerAnglesXYZ", "new", 
	"transitionTo", "processAddChild", "configureAnimationSetOld", 
	"getRigScale", "new", "onFocusReleased", "Move", 
	"OnLastInputTypeChanged", "BindContextActions", "new", 
	"onChild", "onCharacter", "_setupConfigurations", "EnableButton", 
	"getIgnoreList", "DisplayFailureWaypoint", "NewDisplayModel", 
	"PlayFailureAnimation", "new", "CreateTween", "getTrailDotParent", 
	"CheckAlive", "getCollidableExtentsSize", "new", "UnbindContextActions", 
	"OnCurrentGamepadDisconnected", "UnbindContextActions", 
	"GetHighestPriorityGamepad", "Enable", "ConnectFocusEventListeners", 
	"new", "GetClickToMoveController", "UnbindContextActions", 
	"OnMouseLockToggled", "UpdateMouseLockAvailability", "IsValidPartToModify", 
	"Update", "SetMode", "CharacterAdded", "CircleBehavior", 
	"RayIntersection", "addDrift", "GetSubjectPosition", 
	"UpdateFadeFromBlack", "StartFadeFromBlack", 
	"UpdateThirdPersonFollowTransform", "UpdateThirdPersonComfortTransform", 
	"UpdateFirstPersonTransform", "new", "setGoal", "new", 
	"new", "SetAndBoundsCheckElevationValues", "new", "GamepadZoomPress", 
	"setCameraModeToastOpen", "setCameraModeToastEnabled", 
	"SetZoomParameters", "canOcclude", "refreshIgnoreList", 
	"new", "Step", "new", "GetCameraHeight", 
	"CalculateNewLookVectorVRFromArg", "OnEnabledChanged", 
	"GetCameraToggleOffset", "getPanning", "inputEnded", 
	"inputChanged", "inputBegan", "thumbstick", "getRotationActivated", 
	"resetInputForFrameEnd", "thumbstickCurve", "SCurveTranform", 
	"OnLocalPlayerCameraPropertyChanged", "OnCameraTypeChanged", 
	"HandleActivationInput", "CheckMacro", "CheckMouseLockAvailability", 
	"fDeadzone", "fCurve", "Update", "playerRemoving", 
	"newPhysicalPropertiesWithClampedMsgClosure", "pairs", "ipairs", 
	"ConvertCameraModeEnumToStandard", "fromSCurveSpace", 
	"GetAngleBetweenXZVectors", "IsFinite", "Round", "sanitizeAngle", 
	"getLooseBoundingSphere", "mapClamp", "map", "step", 
	"round", "getUser Flag", "disconnectAll", "disconnect", 
	"trackBoundFunction", "trackConnection", "OnMouseLockToggled", 
	"OnPlayerRemoving", "OnCharacterRemoving", "OnCharacterAdded", 
	"OnCurrentCameraChanged", "OnCameraSubjectChanged", 
	"ShouldUseVehicleCamera", "GetClickToMoveController", 
	"GetControls", "GetCameras", "Zero", "Reset", 
	"shallowCopy", "getRelativeVelocity", "map", "loadFlag", 
	"require", "min", "max", "clamp", "sign", "abs", 
	"ceil", "floor", "angle", "dot", "cross", "normalize", 
	"magnitude", "create", "writebits", "readbits", "fill", 
	"copy", "len", "writestring", "readstring", "writef64", 
	"writef32", "writeu32", "writei32", "writeu16", "writei16", 
	"writeu8", "extrapolate", "toolKeyFrameReachedFunc", "playEmote", "Push", "rollAnimation", 
	"scriptChildModified", "onPlatformStanding", "onSeated", "onFallingDown", 
	"onGettingUp", "onDied", "stepAnimate", "switchToAnim", "getToolAnim", 
	"rootMotionCompensation", "findExistingAnimationInSet", "_stopBoundFn", 
	"_startBoundFn", "isManifestResolved", "parsePath", "OnSteerLeft", 
	"OnSteerRight", "OnThrottleDeccel", "OnThrottleAccel", "Enable", 
	"NewDisplayModel", "Create", "destroy", "unbindRoot", "unbindNodeDescend", 
	"onTextFocusGained", "CreateTouchGuiContainer", "SetupAutoPilot", 
	"ComputeSteer", "ComputeThrottle", "_getOrCreateBoundEvent", "getChild", 
	"getCharacter", "getLocalPlayer", "UpdateEnabled", "GetUnreachableWaypointTimeout", 
	"SetUnreachableWaypointTimeout", "GetAgentSizeIncreaseFactor", 
	"SetAgentSizeIncreaseFactor", "GetUseDirectPath", "SetUseDirectPath", 
	"GetIgnoredPartsTag", "GetFailureAnimationEnabled", "SetFailureAnimationEnabled", 
	"GetShowPath", "SetShowPath", "OnRenderStepped", "GetWaypointsAlwaysOnTop", 
	"GetEndWaypointTexture", "GetWaypointRadius", "GetWaypointTexture", 
	"CancelFailureAnimation", "CreateEndWaypoint", "findPlayerHumanoid", 
	"new", "TweenInFrom", "SetIgnoredPartsTag", "GetWaypointsAlwaysOnTop", 
	"SetWaypointsAlwaysOnTop", "GetEndWaypointTexture", "SetEndWaypointTexture", 
	"GetWaypointRadius", "SetWaypointRadius", "GetWaypointTexture", 
	"SetWaypointTexture", "UpdateMovement", "CleanupPath", "DisconnectEvents", 
	"GetCharacter", "findPlayerHumanoid", "FindCharacterAncestor", "OnInputEnded", 
	"Enable", "LayoutMiddleImages", "DoMove", "SwitchToController", 
	"UpdateTouchGuiVisibility", "OnHumanoidSeated", "getGamepadRightThumbstickPosition", 
	"AverageAngle", "UpdateComfortCamera", "processDeleteChild", "processNode", 
	"OnCharacterAdded", "HandleMoveTo", "CreateWaypointTemplates", 
	"placePathWaypoint", "UpdateActiveControlModuleEnabled", "Reset", "Vel", 
	"Update", "queryPoint", "ConnectGamepadConnectionListeners", 
	"OnNewGamepadConnected", "BindContextActions", "UpdateMovement", 
	"Enable", "EnableMouseLock", "GetMouseLockOffset", "new", "new", 
	"axisToCFrame", "new", "__call", "CornerBehavior", "MoveBehavior", 
	"_GetFirstPersonLocalOffset", "_GetThirdPersonLocalOffset", "GetSubjectCFrame", 
	"GetCameraHeight", "UpdateEdgeBlur", "OnCurrentCameraChanged", "ResetZoom", 
	"GamepadZoomPress", "LeaveFirstPerson", "Reset", "_GetFirstPersonLocalOffset", 
	"_GetThirdPersonLocalOffset", "SetCameraToSubjectDistance", 
	"SetInitialOrientation", "StepFreecam", "Pather", "setInputEnabled", 
	"StartFreecam", "getRotation", "enableCameraToggleInput", "MoveStick", 
	"InputInFrame", "FadeThumbstickFrame", "GetIsJumping", 
	"DisconnectGamepadConnectionListeners", "Enable", "GetIsJumping", 
	"IsMoveVectorCameraRelative", "GetMoveVector", "UpdateJump", "_reset", 
	"OnTouchMovementModeChange", "OnComputerMovementModeChange", 
	"OnCharacterRemoving", "OnCharacterAdded", "Disable", "GetActiveController", 
	"NormalizeAngle", "GetMoveVector", "Destroy", "Hide", "GetUser JumpEnabled", 
	"SetUser JumpEnabled", "UpdateJump", "Stop", "Start", "OnTouchEnded", 
	"OnTouchChanged", "OnTouchBegan", "DisconnectEvent", "GetEquippedTool", 
	"maxV", "minV", "IsMouseLocked", "DoMouseLockSwitch", 
	"OnBoundKeysObjectChanged", "GetBindableToggleEvent", "GetIsMouseLocked", 
	"SetSubject", "Enable", "SetupTransparency", "TeardownTransparency", 
	"CachePartsRecursive", "HasToolAncestor", "OnCameraSubjectChanged", 
	"CharacterRemoving", "CharacterAdded", "Enable", "GetOcclusionMode", 
	"Reset", "extractRotation", "cframeToAxis", "Update", "Enable", 
	"GetOcclusionMode", "Cleanup", "GetObscuredParts", "CheckTorsoReference", 
	"LimbMoveBehavior", "LimbBehavior", "Det3x3", "AssertTypes", 
	"yawVelocity", "pitchVelocity", "NormalizeAngle", "GetVRFocus", 
	"OnHeadScaleChanged", "GamepadReset", "GetModuleName", "Reset", 
	"GetAvatarFeetWorldYValue", "setTransform", "step", "getCFrame", 
	"ApplyVRTransform", "GetModuleName", "GetCameraToSubjectDistance", 
	"LoadNumberValueParameters", "SetAndBoundsCheckDistanceValues", 
	"SetAndBoundsCheckAzimuthValues", "LoadOrCreateNumberValueParameter", 
	"getCamera", "Disconnect", "Connect", "Disable", "Enable", 
	"_connectCallbacks", "eraseFromEnd", "getTotalTransparency", 
	"Update", "IsInFirstPerson", "OnNewCameraSubject", 
	"GetHumanoidPartToFollow", "CalculateNewLookVectorFromArg", 
	"GetMeasuredDistanceToFocus", "GetCameraToSubjectDistance", 
	"LeaveFirstPerson", "EnterFirstPerson", "InFirstPerson", 
	"GetMouseLockOffset", "SetMouseLockOffset", "GetIsMouseLocked", 
	"SetIsMouseLocked", "GetCameraMovementMode", "SetCameraMovementMode", 
	"GetCameraType", "SetCameraType", "UpdateForDistancePropertyChange", 
	"GetEnabled", "InputTranslationToCameraAngleChange", 
	"OnPlayerCameraPropertyChange", "GetBodyPartToFollow", "GetModuleName", 
	"Pop", "ActivateCameraController", "keyFrameReachedFunc", 
	"stopAllAnimations", "SelectComputerMovementModule", "Reset", 
	"queryViewport", "StartCapture", "ReleaseSpring", "GetZoomRadius", 
	"GetHumanoid", "GetCameraLookVector", "Cleanup", "OnCurrentCameraChanged", 
	"OnViewportSizeChanged", "GetSubjectRotVelocity", "GetSubjectVelocity", 
	"GetHumanoidRootPart", "SetCameraMovementMode", "setTogglePan", 
	"getTogglePan", "getHoldPan", "getInputEnabled", "resetPanInputCount", 
	"decPanInputCount", "incPanInputCount", "pointerAction", "gamepadReset", 
	"gamepadZoomPress", "keypress", "mouseWheel", "mouseMovement", 
	"isInDynamicThumbstickArea", "adjustTouchPitchSensitivity", "getMouse", 
	"toSCurveSpace", "RotateVectorByAngleAndRound", "IsFiniteVector3", 
	"OnPlayerAdded", "Update", "OnUser GameSettingsPropertyChanged", 
	"MouseWheel", "Trigger", "Thumb", "MousePan", "GpButton", 
	"Keypress", "characterRemoving", "characterAdded", "OnTap", 
	"initializeSoundSystem", "playToolAnimation", "StopFreecam", 
	"Pan", "SetWaypointsAlwaysOnTop", "SetEndWaypointTexture", 
	"SetWaypointRadius", "SetWaypointTexture", "SmartCircleBehavior", 
	"UpdateStepRotation", "UpdateRotationCamera", "StartVREdgeBlur", 
	"UpdateImmersionCamera", "getCollisionPoint", "updateProjection", 
	"testPromotion", "UpdateMouseBehavior", "GetSubjectCFrame", 
	"resetTouchState", "onFreeFall", "onJumping", "stopToolAnimations", 
	"setAnimationSpeed", "setRunSpeed", "getHeightScale", "CleanupPath", 
	"getTrailDotScale", "createTrailDots", "Enable", "SelectTouchModule", 
	"CharacterOutlineBehavior", "Update", "step", "Popper", 
	"playerRemoving", "playerAdded", "StepZoom", "touchChanged", 
	"touchEnded", "touchBegan", "GetCameraControlChoice", 
	"ActivateOcclusionModule", "GetCameraMovementModeFromSettings", 
	"Fov", "thumbstickCurve", "call", "animateTool", "onSwimming", 
	"onClimbing", "playAnimation", "terminate", "stopPlayingLoopedSounds", 
	"configureAnimationSet", "ToggleFreecam", "bindRoot", "Update", 
	"onLocalPlayer", "ShowPathFailedFeedback", "getFailureAnimationTrack", 
	"MoveTo", "Raycast", "Create", "DoFadeInBackground", "FadeThumbstick", 
	"BindContextActions", "updateVRMoveVector", "OnRenderStepped", 
	"calculateRawMoveVector", "GetEstimatedVRTorsoFrame", "Update", 
	"Step", "getRotation", "CalculateNewLookVector", "updateBounds", 
	"stepTargetZoom", "CalculateNewLookCFrameFromArg", 
	"SetCameraToSubjectDistance", "OnCharacterAdded", "_setUpConfigurations", 
	"disableCameraToggleInput", "restoreRotationType", "setRotationTypeOverride", 
	"restoreMouseBehavior", "setMouseBehaviorOverride", "restoreMouseIcon", 
	"setMouseIconOverride", "GamepadLinearToCurve", "onAxis", 
	"playerAdded", "onRunning", "StopCapture", "UpdateIgnoreTag", 
	"CreatePathDisplay", "RunFailureTween", "BindContextActions", 
	"_StepRotation", "OnEnabledChanged", "GetSubjectPosition", 
	"resetInputDevices", "getZoomDelta", "setSoundLooped", 
	"playSoundIf", "stopSound", "playSound", "loadmodule", 
	"require", "assert", "pcall", "setthreadidentity", 
	"getthreadidentity", "getscriptbytecode", "pcall", "typeof", 
	"disassemble", "decompile", "getcustomasset", "setproperties", 
	"getproperties", "readfileasync", "readfile", "isfolder", 
	"delfolderasync", "delfolder", "movefolderasync", "movefolder", 
	"copyfolder", "makefolder", "listfiles", "isfile", "dofile", 
	"loadfile", "delfile", "movefile", "copyfile", "appendfile", 
	"writefile", "connect", "restoremetamethod", "hookmetamethod", 
	"getmetafield", "hasmetafield", "hasmetatable", "setreadonly", 
	"setrawmetatable", "getrawmetatable", "isreadonly", 
	"getdatamodeltype", "setcalltrace", "getbytecode", "setfpscap", 
	"getfpscap", "setthreadidentity", "getthreadidentity", 
	"gethwid", "can_vm_run_native_code", "isnativecode", 
	"disablenative", "enablenative", "enablepointerencoding", 
	"disablepointerencoding", "getstringatom", "getstringhash", 
	"isinstance", "request", "validlevel", "getupvaluecount", 
	"getconstantcount", "getstackcount", "traceback", "info", 
	"getinfo", "setstack", "getstack", "setupvalue", "getupvalue", 
	"getupvalues", "setconstant", "getconstants", "getconstant", 
	"trampoline_call", "ishiddenstack", "sethiddenstack", 
	"comparefunction", "getfunctionhash", "protectfunction", 
	"loadstring", "restorefunction", "iswrappedclosure", 
	"isfunctionprotected", "hookfunction", "clonefunction", 
	"isexecutorclosure", "ishooked", "wrapclosure", "newcclosure", 
	"newlclosure", "islclosure", "iscclosure", "getinstancelist", 
	"getinstances", "getnilinstances", "getconnections", "gethui", 
	"firetouchinterest", "fireproximityprompt", "fireclickdetector", 
	"getsenv", "getcallingscript", "getscriptbytecode", 
	"getscriptclosure", "exchangeinstancepointer", "getsignalargumenttypes", 
	"getsignalargumentnames", "gethiddenproperty", "getcallbackvalue", 
	"invalidatereference", "replacereference", "isreferencevalid", 
	"compareinstances", "cloneref", "stepgc", "gc", "isreferenced", 
	"getgc", "resumegc", "suspendgc", "setclipboard", "gettenv", 
	"messagebox", "httpget", "identifyexecutor", "getscriptglobals", 
	"getgenv", "getreg", "setclipboard", "gettenv", "messagebox", 
	"httpget", "identifyexecutor", "getscriptglobals", "getgenv", 
	"getreg", "DebuggerManager", "cancel", "wait", "delay", 
	"spawn", "defer", "desynchronize", "synchronize", "setfenv", 
	"getfenv", "collectgarbage", "Version", "version", "Stats", 
	"stats", "require", "warn", "PluginManager", "User Settings", 
	"settings", "loadstring", "printidentity", "Spawn", "spawn", 
	"Delay", "delay", "Wait", "wait", "ElapsedTime", "elapsedTime", 
	"time", "tick", "print", "fromCurrent", "new", "fromObject", 
	"fromAssetId", "fromUri", "fromId", "fromName", "fromEnum", 
	"new", "fromIsoDate", "fromLocalTime", "fromUniversalTime", 
	"fromUnixTimestampMillis", "fromUnixTimestamp", "now", "new", 
	"new", "new", "new", "new", "new", "new", "new", "new", 
	"new", "new", "new", "new", "new", "fromExisting", "new", 
	"clear", "update", "size", "increment", "cloneAndFreeze", 
	"clone", "isFrozen", "new", "new", "new", "new", "fromScale", 
	"fromOffset", "new", "new", "Blue", "Green", "Yellow", "Red", 
	"Black", "DarkGray", "Gray", "White", "Random", "New", 
	"palette", "random", "new", "fromHex", "fromHSV", "toHSV", 
	"fromRGB", "new", "new", "max", "min", "new", "max", 
	"min", "fromAxis", "FromAxis", "fromNormalId", "FromNormalId", 
	"new", "new", "new", "new", "new", "new", "fromRotationBetweenVectors", 
	"lookAlong", "lookAt", "fromMatrix", "fromAxisAngle", 
	"fromEulerAngles", "fromOrientation", "fromEulerAnglesYXZ", 
	"Angles", "fromEulerAnglesXYZ", "new", "transitionTo", 
	"processAddChild", "configureAnimationSetOld", "getRigScale", 
	"new", "onFocusReleased", "Move", "OnLastInputTypeChanged", 
	"BindContextActions", "new", "onChild", "onCharacter", 
	"_setupConfigurations", "EnableButton", "getIgnoreList", 
	"DisplayFailureWaypoint", "NewDisplayModel", "PlayFailureAnimation", 
	"new", "CreateTween", "getTrailDotParent", "CheckAlive", 
	"getCollidableExtentsSize", "new", "UnbindContextActions", 
	"OnCurrentGamepadDisconnected", "UnbindContextActions", 
	"GetHighestPriorityGamepad", "Enable", "ConnectFocusEventListeners", 
	"new", "GetClickToMoveController", "UnbindContextActions", 
	"OnMouseLockToggled", "UpdateMouseLockAvailability", "IsValidPartToModify", 
	"Update", "SetMode", "CharacterAdded", "CircleBehavior", 
	"RayIntersection", "addDrift", "GetSubjectPosition", 
	"UpdateFadeFromBlack", "StartFadeFromBlack", 
	"UpdateThirdPersonFollowTransform", "UpdateThirdPersonComfortTransform", 
	"UpdateFirstPersonTransform", "new", "setGoal", "new", 
	"new", "SetAndBoundsCheckElevationValues", "new", "GamepadZoomPress", 
	"setCameraModeToastOpen", "setCameraModeToastEnabled", 
	"SetZoomParameters", "canOcclude", "refreshIgnoreList", 
	"new", "Step", "new", "GetCameraHeight", 
	"CalculateNewLookVectorVRFromArg", "OnEnabledChanged", 
	"GetCameraToggleOffset", "getPanning", "inputEnded", 
	"inputChanged", "inputBegan", "thumbstick", "getRotationActivated", 
	"resetInputForFrameEnd", "thumbstickCurve", "SCurveTranform", 
	"OnLocalPlayerCameraPropertyChanged", "OnCameraTypeChanged", 
	"HandleActivationInput", "CheckMacro", "CheckMouseLockAvailability", 
	"fDeadzone", "fCurve", "Update", "playerRemoving", 
	"newPhysicalPropertiesWithClampedMsgClosure", "pairs", "ipairs", 
	"ConvertCameraModeEnumToStandard", "fromSCurveSpace", 
	"GetAngleBetweenXZVectors", "IsFinite", "Round", "sanitizeAngle", 
	"getLooseBoundingSphere", "mapClamp", "map", "step", 
	"round", "getUser Flag", "disconnectAll", "disconnect", 
	"trackBoundFunction", "trackConnection", "OnMouseLockToggled", 
	"OnPlayerRemoving","GetUserJumpEnabled", "SetUserJumpEnabled", "OnUserGameSettingsPropertyChanged", 
	"getrenv", "User Settings", "getUser Flag", "writei8", "readf64", 
	"readf32", "readu32", "readi32", "readu16", "readi16", 
	"readu8", "readi8", "tostring", "fromstring", "clock", 
	"difftime", "date", "byteswap", "countrz", "countlz", 
	"rshift", "rrotate", "replace", "lshift", "lrotate", 
	"extract", "btest", "bxor", "bor", "bnot", 
	"band", "arshift", "nfdnormalize", "nfcnormalize", 
	"graphemes", "codes", "char", "codepoint", "offset", 
	"dumpcodesize", "dumprefs", "dumpheap", "resetmemorycategory", 
	"setmemorycategory", "getmemorycategory", "profileend", 
	"profilebegin", "unpack", "isfrozen", "freeze", "find", 
	"move", "pack", "sort", "remove", "insert", 
	"maxn", "getn", "foreachi", "foreach", "concat", 
	"lerp", "noise", "tan", "tanh", "sqrt", 
	"sin", "sinh", "randomseed", "rad", "pow", 
	"modf", "log", "log10", "ldexp", "frexp", 
	"fmod", "exp", "deg", "cos", "cosh", 
	"atan", "atan2", "asin", "acos", "unpack", 
	"packsize", "pack", "split", "upper", "sub", 
	"reverse", "rep", "match", "lower", "gsub", 
	"gmatch", "format", "find", "char", "byte", 
	"resume", "close", "isyieldable", "yield", "wrap", 
	"status", "running", "xpcall", "type", "tostring", 
	"tonumber", "setmetatable", "select", "rawlen", 
	"rawset", "rawget", "rawequal", "newproxy", "next", 
	"getmetatable", "gcinfo", "error", "UserSettings", "getUserFlag"
}
